### ISSUE TITLE
undefined method when migrating

### ISSUE THREAD

**Issue by matejzero** [sndl/phab-to-gitlab#1]
Hello,

I'm trying to use your script to migrate tickets but I seem to hit a problem with both, user and ticket arg.

```
./migrate.rb  user
/phab/lib/phabricator.rb:62:in `block in paginate': undefined method `[]' for nil:NilClass (NoMethodError)
	from /phab/lib/phabricator.rb:60:in `loop'
	from /phab/lib/phabricator.rb:60:in `paginate'
	from /phab/lib/phabricator.rb:19:in `user_search'
	from ./migrate.rb:28:in `migrate_user'
	from ./migrate.rb:129:in `<main>'
```

Ruby is not my thing, so I'm not sure where to look for problems. Can you let me know where the problem could be?

**Comment by sndl** [comment]
Hi Matej,

If you can put after this line `response = JSON.parse(RestClient.post(url, payload).body)['result']` following line: `puts response` and provide me the output I can try to debug it.

P.S. don't forget to cut out sensitive data

**Comment by matejzero** [comment]
Hey,

Thanks for quick answer. I did some debuging and found out I have an old
installation of Phabricator which doesn't have user.search function.

I tried replacing it with user.query, but i get another error. I will try
upgrading Phab to latest release and tried again.

On 29 Jun 2017, at 16:51, sndl <notifications@github.com> wrote:

Hi Matej,

If you can put after this line response = JSON.parse(RestClient.post(url,
payload).body)['result'] following line: puts response and provide me the
output I can try to debug it.

P.S. don't forget to cut out sensitive data

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/sndl/phab-to-gitlab/issues/1#issuecomment-311991108>,
or mute the thread

**Comment by sndl** [comment]
Hi, did you manage to migrate the data?

**Comment by matejzero** [comment]
Hey there,

not yet:( I have to upgrade Phabricator to a newer version but I'm busy with other tasks. It everything will go as planned, I will give it a go tomorrow.

**Comment by matejzero** [comment]
I updated phabricator to latest version and tried migrating with your script and I get:

```
$ ./migrate.rb user
/.../phab-to-gitlab/lib/phabricator.rb:48:in `private': nil is not a symbol (TypeError)
	from /.../phab-to-gitlab/lib/phabricator.rb:48:in `<class:Phabricator>'
	from /.../phab-to-gitlab/lib/phabricator.rb:4:in `<top (required)>'
	from ./migrate.rb:8:in `require_relative'
	from ./migrate.rb:8:in `<main>'
```

Is there an easy fix?

**Comment by matejzero** [comment]
I run ruby 2.4 in docker and I don't get that error anymore. I do, on the other hand, get the same error as before:
```
/migrate/lib/phabricator.rb:63:in `block in paginate': undefined method `[]' for nil:NilClass (NoMethodError)
	from /migrate/lib/phabricator.rb:60:in `loop'
	from /migrate/lib/phabricator.rb:60:in `paginate'
	from /migrate/lib/phabricator.rb:19:in `user_search'
	from ./migrate.rb:58:in `block (2 levels) in migrate_ticket'
	from ./migrate.rb:49:in `each'
	from ./migrate.rb:49:in `block in migrate_ticket'
	from ./migrate.rb:41:in `each'
	from ./migrate.rb:41:in `migrate_ticket'
	from ./migrate.rb:131:in `<main>'
```

I tried putting `puts JSON.parse(RestClient.post(url, payload).body)['result']` before line 63 and I can see Phabricator returning a document:
```
{"data"=>[{"id"=>399, "type"=>"TASK", "phid"=>"PHID-TASK-py6s4wb56f5fasdqss2i", "fields"=>{"name"=>"test1", "description"=>{"raw"=>"test"}, "authorPHID"=>"PHID-USER-xuquvdm5o7grvsleggyt", "ownerPHID"=>"PHID-USER-xuquvdm5o7grvsleggyt", "status"=>{"value"=>"open", "name"=>"Open", "color"=>nil}, "priority"=>{"value"=>90, "subpriority"=>0, "name"=>"Needs Triage", "color"=>"violet"}, "points"=>nil, "subtype"=>"default", "spacePHID"=>nil, "dateCreated"=>1498744190, "dateModified"=>1498744208, "policy"=>{"view"=>"users", "interact"=>"users", "edit"=>"users"}, "custom.foobar:customer-id"=>nil, "custom.foobar:otrs-id"=>nil, "custom.foobar:server-id"=>nil, "custom.foobar:contact-person"=>nil, "custom.foobar:contact-mail"=>nil, "custom.foobar:contact-phone"=>nil}, "attachments"=>{}}], "maps"=>{}, "query"=>{"queryKey"=>nil}, "cursor"=>{"limit"=>100, "after"=>nil, "before"=>nil, "order"=>"oldest"}}
```
